/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BFormRadio: typeof import('bootstrap-vue-next')['BFormRadio']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BTbody: typeof import('bootstrap-vue-next')['BTbody']
    BTd: typeof import('bootstrap-vue-next')['BTd']
    BTh: typeof import('bootstrap-vue-next')['BTh']
    BThead: typeof import('bootstrap-vue-next')['BThead']
    BTr: typeof import('bootstrap-vue-next')['BTr']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    IOpenmojigithub: typeof import('~icons/openmoji/github')['default']
    IRaphaelgithub: typeof import('~icons/raphael/github')['default']
    NamePopover: typeof import('./src/components/NamePopover.vue')['default']
    PathTable: typeof import('./src/components/PathTable.vue')['default']
    SelectForm: typeof import('./src/components/SelectForm.vue')['default']
    ShowCode: typeof import('./src/components/ShowCode.vue')['default']
    TableRow: typeof import('./src/components/TableRow.vue')['default']
  }
}
